# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-10 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180408_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subject',
            field=models.CharField(choices=[('Angular', 'Angular'), ('Ionic', 'Ionic'), ('Drf', 'Drf'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
