# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-10 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_remove_comment_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='article_com',
        ),
    ]
