# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-10 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20180410_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article_com',
            new_name='article',
        ),
    ]
